### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by swetha-thoomoju** [guikeller/cordova-watchconnectivity-plugin#1]
Hi,

When I tried to build my code am facing the following issue.

`
error: Invalid bitcode signature
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Later I figured out this is due to using  .a library instead of .h and .m, For the time being I fixed the issue by creating a local repo previous to using library file.

Thanks for the plugin, I could make some process 👍

**Comment by guy-keller** [comment]
Thanks for the feedback @swetha-thoomoju 
To be honest with you I haven't had the chance to test with the ".a" library.

I've chosen to distribute a ".a" because then I can have XCode configured for the plugin development.
https://github.com/guikeller/cordova-watchconnectivity-plugin-source

I will have some time over the weekend to look into it and should be able to resolve this issue.
Glad to hear that the plugin has helped you make some progress!

PS: I have found the issue, I _forgot_ to "**enable bitcode**", I will do a new build of the lib to fix this issue.
https://medium.com/@heitorburger/static-libraries-frameworks-and-bitcode-6d8f784478a9

**Comment by guy-keller** [comment]
Hi @swetha-thoomoju,

Would you mind giving it a go again and letting me know if it is fine?
Otherwise, I will revert to using the .h and .m source files instead.

Thanks!

**Comment by swetha-thoomoju** [comment]
Sure, will check that tomorrow.

**Comment by guy-keller** [comment]
Thanks @swetha-thoomoju,

Looking forward to getting some feedback.

Cheers

**Comment by guy-keller** [comment]
Hi @swetha-thoomoju,

Did you manage to see if it works for you?

Thanks!

**Comment by swetha-thoomoju** [comment]
Hi @guikeller,

I see a different issue 
> ld: framework not found WCiOS
clang: error: linker command failed with exit code 1 (use -v to see invocation)
** BUILD FAILED **

So I cloned your project from here
https://github.com/guikeller/cordova-watchconnectivity-plugin-source

And tried building in Xcode, I see the following error (Not sure if it suppose to work)
![Screen Shot 2019-04-03 at 3 18 32 PM](https://user-images.githubusercontent.com/20985225/55469807-e35edd80-5623-11e9-9455-b4b46f8d3424.jpg)

I tried the suggestions mentioned here
https://medium.com/@heitorburger/static-libraries-frameworks-and-bitcode-6d8f784478a9, but no luck.

I am not that familiar with the iOS, so trying to understand how libraries will work.

Let me know if there is anything I can try.

**Comment by guy-keller** [comment]
That is simple to fix, on the checked out directory double click on
"cordova-watchconnectivity-plugin.**xcworkspace**"

I will revert back to using a " .h and .m " file for the plugin then.
Thanks for your help! I should get that done shortly.

**Comment by guy-keller** [comment]
Just committed the latest changes, it all should work just fine now.
Unfortunately, I couldn't figure out why the **.framework** or **.a** (lib) approach did not work.
